### PR TITLE
Upgrading meshery-linkerd adapter to v2 for all centralised e2e tests

### PR DESCRIPTION
**Pull request by yash37158**
**Description**

This PR fixes:  Need to upgrade core adapters to v2 for all centralised e2e test #497

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — COMMENTED** [review]
Hi, thanks for your contribution. May you help us identify if the e2e test cases in this repo are useful? As you can see they are always failed.

**Comment by yash37158** [comment]
Yeah sure @Aisuko , I'll look into that

**Comment by Revolyssup** [comment]
@yash37158 Can you fix lint tests?

**Comment by yash37158** [comment]
Yeah sure @Revolyssup, but ayush is already working on that

**Pull request closed without merging**
