### PR TITLE
Update go version in relevent pkgs

### LINKED ISSUE #545: [chore] update Go to 1.21, and update relevant pkgs
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

### PR DESCRIPTION
**Pull request by ShatilKhan**
**Description**

This PR fixes #545

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

I updated the `go` version from `1.19` to `1.21` in `go.mod` & `Dockerfile`

### CODE REVIEW

**Comment by leecalcote** [comment]
@Revolyssup will you review?

**Comment by leecalcote** [comment]
Running build checks

**Comment by Aisuko** [comment]
> Running build checks

Hi @leecalcote sir. I saw many times the (E2E) multiple versions tests failed. Many of them failed because Meshery service cannot run in the Action environment. Is there anything we are missing?

**Comment by Aisuko** [comment]
https://github.com/meshery/meshery/issues/8768

**Comment by theBeginner86** [comment]
> > Running build checks
> 
> Hi @leecalcote sir. I saw many times the (E2E) multiple versions tests failed. Many of them failed because Meshery service cannot run in the Action environment. Is there anything we are missing?

yes, I think we discussed this a bit on Slack. Its due to mesheryctl use of `kubectl version --client --short` but recently in K8s v1.28.0 `--short` flag has been deprecated ([reference](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#deprecation)). So we need to update our use to `kubectl version`. 
Reference to slack conversation: https://layer5io.slack.com/archives/C011VPREG2Z/p1693831894773679

**Comment by Aisuko** [comment]
> > > Running build checks
> > 
> > 
> > Hi @leecalcote sir. I saw many times the (E2E) multiple versions tests failed. Many of them failed because Meshery service cannot run in the Action environment. Is there anything we are missing?
> 
> yes, I think we discussed this a bit on Slack. Its due to mesheryctl use of `kubectl version --client --short` as recently in K8s v1.28.0 `--short` flag has been deprecated ([reference](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#deprecation)). So we need to update our use to `kubectl version`. Reference to slack conversation: https://layer5io.slack.com/archives/C011VPREG2Z/p1693831894773679

Noticed and thanks.

**Comment by ShatilKhan** [comment]
Hi, is this PR good to merge?

**Review by Aisuko — APPROVED** [review]
approved

**Pull request merged**
