### PR TITLE
updated adapter name in component_info.json

### PR DESCRIPTION
**Pull request by asubedy**
**Description**
Update the name of adapter in `component_info.json` for uniformity on naming components

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by warunicorn19** [comment]
oops, look like you forgot to sign off your PR.

**Comment by asubedy** [comment]
Closing this one will create a new one after adding signoff.

**Comment by sayantan1413** [comment]
Hey @asubedy you can check these steps https://github.com/meshery/meshery-linkerd/pull/276/checks?check_run_id=4610813036 for the DCO issue.

**Comment by asubedy** [comment]
@warunicorn19 can we add signoff to the commits we made on the web itself?

**Comment by warunicorn19** [comment]
Nope, to add the sign-off you'd have to fork, then clone the repo and then make the PR

**Comment by asubedy** [comment]
Ok, thank you I will be closing this PR. Sorry for any inconvenience.

**Comment by warunicorn19** [comment]
No problem @asubedy 😄

**Pull request closed without merging**
