### PR TITLE
Fixed CI state issue

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: aisuko <urakiny@gmail.com>

**Description**

We got the CI issue with go statticcheck, but when I was check it at local, it doesn't report any error. So, I'd like to update the CI process to follow the latest official Github Action example and to solve this.https://staticcheck.io/docs/running-staticcheck/github-actions/

Screenshot 2021-12-07 at 8 34 40 AM

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
I need to fix the new error were checked by the staticcheck Github action on our code. As we can see the staticcheck logic is working well. https://github.com/meshery/meshery-linkerd/runs/4451238855?check_suite_focus=true

**Comment by Revolyssup** [comment]
> 

Can you still make the changes asked in static check , so that all tests pass before we merge?
If it works fine, we can reuse the same github action across all adapters

**Comment by Aisuko** [comment]
> Can you still make the changes asked in static check , so that all tests pass before we merge?
> If it works fine, we can reuse the same github action across all adapters

No problems. I will fix the error later.

**Comment by Aisuko** [comment]
Please help to take a look guys and after we merge this one. The confused on other PR can be solved.

**Review by jbyers19 — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
Looking good!

**Pull request merged**
