### PR TITLE
[meshery-linkerd] updated go.mod version to 1.17 and updated dependencies

### PR DESCRIPTION
**Pull request by jbyers19**
Signed-off-by: Jared Byers <j.byers@f5.com>

**Description**
The static checks action is failing. This change is to try and resolve this issue and unblock other PRs from being merged.

I changed the go version to `1.17` in `go.mod` to match the version of go used when compiling. Ran `go mod tidy` to update dependencies. Aside from changing the go version, the remaining changes are all generated during `go mod tidy`.

**Notes for Reviewers**
I ran staticcheck locally and did not see any errors, so hopefully this fixes the issue.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by jbyers19** [comment]
The check is still failing with these changes. 😞 @Aisuko, any idea how to fix this?

**Comment by Aisuko** [comment]
> The check is still failing with these changes. 😞 @Aisuko, any idea how to fix this?

Thakns for the contributing @jbyers19. In fact, we hit same issue here, let's merge that PR first https://github.com/meshery/meshery-linkerd/pull/256

So, the error may not related to your PR.

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
@jbyers19 Thanks.

**Pull request merged**
