### PR TITLE
[Draft] Bump the distroless image tag to fix cves

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: aisuko <urakiny@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
The security issues of images can divide into `operating-system` and `container-runtime`. I believe we can fixed up the `operating-system` base security issue by updating the base image tag like above. The `container-runtime` security issue we can update the `container-runtime` version.

**Comment by Aisuko** [comment]
https://github.com/meshery/meshery/issues/4642

**Review by leecalcote — APPROVED** [review]
Lgtm

**Comment by s1ntaxe770r** [comment]
one tests seems to be failing @Aisuko

**Review by s1ntaxe770r — APPROVED** [review]

**Comment by Aisuko** [comment]
> one tests seems to be failing @Aisuko, other than that LGTM

Thanks, the CI issue I have mentioned at other PR.

**Pull request merged**
