### PR TITLE
[UX] Minor update on spelling and logs

### PR DESCRIPTION
**Pull request by leecalcote**

### CODE REVIEW

**Comment by warunicorn19** [comment]
I beat you to it, but I'll close my PR because this has more changes.😅

**Comment by leecalcote** [comment]
Oh! Too funny. I didn't see yours. Let's merge yours and I'll refactor mine with any merge conflicts as needed.

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
HI guys, It looks like doesn't exist any conflictions. I'm going to merge this one now.

**Pull request merged**
