### PR TITLE
Normalizing behavior with other adapters and add components

### PR DESCRIPTION
**Pull request by Revolyssup**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
We're using the `build` package in all adapters, yes?

**Comment by Revolyssup** [comment]
> We're using the `build` package in all adapters, yes?

Yes

**Comment by leecalcote** [comment]
Gotcha. Thanks for confirming.

**Comment by leecalcote** [comment]
Hmm. Failed integration test...

**Comment by leecalcote** [comment]
Failure expected here, @Revolyssup ?

**Comment by Revolyssup** [comment]
> Failure expected here, @Revolyssup ?

The e2e tests are still failing. I'm working on that.

**Pull request closed without merging**
