### PR TITLE
fix a misused meshkit logger

### PR DESCRIPTION
**Pull request by Shreyas220**
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>

**Description**

This PR fixes an instance of a misused meshkit logger

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — CHANGES_REQUESTED** [review]
Please help to fix the checking issue.

**Review by Revolyssup — APPROVED** [review]

**Comment by Revolyssup** [comment]
@Shreyas220  merge conflixts to resolve

**Comment by Aisuko** [comment]
Please rebase the latest code from the master branch.

**Comment by Shreyas220** [comment]
@Aisuko @Revolyssup  I think this PR is no longer needed 
meshkit error is handled in AnnotateNamespace() function in [linkered.go](https://github.com/meshery/meshery-linkerd/blob/ea7bc61e28b90d434affaef048633779e1a77e28/linkerd/linkerd.go#L209)

**Pull request closed without merging**
