### PR TITLE
Add support for patterns

### PR DESCRIPTION
**Pull request by utkarsh-pro**
**Description**

This PR adds support for Patterns.

**Notes for Reviewers**
DO NOT MERGE, DRAFT PR.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by DelusionalOptimist** [comment]
@utkarsh-pro Would be nice to get in https://github.com/meshery/meshery-linkerd/issues/220 first for this?

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist yeah that's why it is marked draft

**Comment by DelusionalOptimist** [comment]
Cool. Adding it quickly :sweat_smile:

**Comment by utkarsh-pro** [comment]
Oh no issues. This PR can go ahead without the components too. The default CRDs would be just cherry on top :stuck_out_tongue:

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
