### PR TITLE
Updated condition for action to run

### LINKED ISSUE #380: [CI] Trigger Component Documentation after generation of components
@asubedy [this workflow](https://github.com/meshery/meshery-linkerd/actions/runs/2792271456) should probably be embedded within or trigger from the completion of components being generated, not triggered on merge to master.

_Originally posted by @leecalcote in https://github.com/meshery/meshery-linkerd/issues/369#issuecomment-1204447773_

### PR DESCRIPTION
**Pull request by asubedy**
Signed-off-by: asubedy <frexpe@pm.me>

**Description**
Now the workflow runs only when there is some changes on `templates/oam/workloads` folder.

This PR fixes #380 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
No, it should run as part of the scheduled component generation workflows.

**Comment by asubedy** [comment]
@leecalcote  This workflow does run after any changes on the workflow folder is pushed. Do we want a single workflow that handles Component generation and pushes the changes to the meshery repo?

Thus basically adding more steps on https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/update-oam-defs.yml

**Comment by Revolyssup** [comment]
@asubedy  We want this workflow to run on per PR, so we cant have this change. What is the desired goal?

**Comment by leecalcote** [comment]
@asubedy this issue has stagnated. Please join the Meshery CI meeting to discuss, if that's helpful.

**Comment by leecalcote** [comment]
@Revolyssup @asubedy please complete this task.

**Pull request merged**
