### PR TITLE
Ciupdates

### LINKED ISSUE #491: CI: The CI needs to be more simple and more clearly
#### Current Behavior

1. The CI process is triggered by every PR and most time it failed. 
2. All the CIs are triggered by the new PR.
3. The test adapter CIs are failed all time.

#### Desired Behavior

1. We should let the CI simpler it is only responsible to check the code quality.
2. We should make sure the specific CI is triggered by different PR(golang->golang, yaml->yaml)
3. The test adapter CIs should be useful. If it were not useful, we can remove it. we do not want to waste the resources.
image

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by duckling69**
**Description**

This PR fixes #491 

**Notes for Reviewers**
>removed test adapters
>ci will be only triggered with specific job on specific code change 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by duckling69** [comment]
**Changes**

- Removed testadapter as mentioned 
image

-Added path Fiters for go and yaml and specified jobs for each of them seperately

@Aisuko @leecalcote might take a look and give review

**Comment by Revolyssup** [comment]
Please undo the changes in e2etest.yaml. You can add `*.go` in`paths` for e2etest.yaml but you cant essentially outright remove the most important job. The job you removed makes the workflow meaningless.

**Review by Revolyssup — CHANGES_REQUESTED** [review]
Please undo the changes in e2etest.yaml. You can add *.go inpaths for e2etest.yaml but you cant essentially outright remove the most important job. The job you removed makes the workflow meaningless.

**Comment by duckling69** [comment]
Hey @Aisuko can you look into pr I've made all reviewed changes If any further changes to be made

**Comment by Aisuko** [comment]
> Hey @Aisuko can you look into pr I've made all reviewed changes If any further changes to be made

Let's invite @Revolyssup to take a look at this. Make sure he also agrees with this solution.

**Review by Revolyssup — APPROVED** [review]

**Comment by Aisuko** [comment]
@duckling69 Thank you.

**Pull request merged**
