### PR TITLE
deploy linkerd stable channel

### LINKED ISSUE #448: Deploy from Linkerd's stable channel by default
#### Current Behavior

MeshOps V1 picks up latest version(edge or stable) to deploy Linkerd Service Mesh.
#### Expected Behavior

While using MeshOps V1 where the users do not specify a particular version, prioritise the installation of latest stable over edge.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by duckling69**
**Description**

This PR fixes #448 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by duckling69** [comment]
**Previous behavior**

image


**Current behavior**

image

**Review by Aisuko — CHANGES_REQUESTED** [review]
Thank you, please check the confliction.

**Comment by duckling69** [comment]
> Thank you, please check the confliction.

fixed

**Review by Aisuko — APPROVED** [review]
LGTM

**Pull request merged**
