### PR TITLE
Upgrade Go 1.19

### PR DESCRIPTION
**Pull request by acald-creator**
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Description**

This PR is related to https://github.com/meshery/meshery/issues/6220

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@Revolyssup ready to merge?

**Comment by leecalcote** [comment]
@Revolyssup LGTY?

**Review by leecalcote — APPROVED** [review]
We might move to `@latest` or `@master`, but LGTM

**Review by Revolyssup — APPROVED** [review]

**Comment by leecalcote** [comment]
@Revolyssup the failed tests?

**Comment by leecalcote** [comment]
(Do we need to be concerned with those?)

**Comment by Revolyssup** [comment]
> Details

Yes I am looking at these tests. These are failing independently of this PR. We can merge this PR

**Comment by leecalcote** [comment]
Good! :)

**Comment by leecalcote** [comment]
Whoo-hoo, @acald-creator! 🎈

**Pull request merged**
